baseURL = 'https://siliconguilleries.github.io'
theme = 'spectral'
copyright = 'This works is license under a Creative Commons Attribution-ShareAlike 4.0 International license'
title = 'Silicon Guilleries'

# Content
paginate = 10
builddrafts = false
enableEmoji = true

# Languages
defaultContentLanguage = 'ca'
defaultContentLanguageInSubdir = false

# Menus
#sectionPagesMenu = 'main'

# Parameters
[params]
body_is_markdown = true
# copyright = ''
# startbuttonText = ''
# startbuttonLink = ''
custom_css = 'css/siliconguilleries.css'

[params.social]
github = 'siliconguilleries'
x = 'siguilleries'
discord = 'gsjVvHnXYd'
# instagram = ''
# youtube = ''
# mastodon = ''
# facebook = ''
# dribble = ''

[taxonomies]
tag = 'tags'
category = 'categories'
