languageCode = 'en'
languageDirection = 'ltr'
languageName = 'English'
title = 'Silicon Guilleries'
weight = 10

[params]
fancyTitle = 'Silicon Guilleries'
description = 'The Guilleries tech comunity'

[params.one]
enable = true
body = '''
Silicon Guilleries is born with the goal of being the tech community of the Guilleries, where
everybody with some interest in technology participates somehow.

Nowadays, technology is almost present everywhere. Silicon Guilleries aims to gather all the people
who use technology professionally or as a hobby to create systems, automate processes, improve
certain daily tasks, etc.

The organization of tech meetup, hackathons, or events of the topics that you propose will be the
starting point to build the foundations of Silicon Guilleries.
'''

[params.three]
enable = true
title = "Main goal"
body = '''
To Gather people of the area with general or specific technological interests to organize
talks, meetups, and events (e.g. hackathons), in order to improve our skills and learn together.

To achieve it, we need
'''
[[params.three.feature]]
icon = 'fa-user'
body ='You sign up to know that you are part of this collective'
[[params.three.feature]]
icon = 'fa-lightbulb'
body ='You propose talks, events, or activities that could be of our interests'

[params.cta]
enable = true
title = "What are you waiting for?"
body = "Sign up as a member and join to our Discord"
[[params.cta.link]]
href = "sign-up-member"
text = "Sign up"
special = true
[[params.cta.link]]
href = "https://discord.gg/gsjVvHnXYd"
text = "Discord"
special = false
