languageCode = 'ca'
languageDirection = 'ltr'
languageName = 'Català'
title = 'Silicon Guilleries'
weight = 1

[params]
fancyTitle = 'Silicon Guilleries'
description = 'La comunitat tecnològica de les Guilleries'

[params.one]
enable = true
body = '''
Silicon Guilleries té l'objectiu de ser una comunitat tecnològica creada a Sant Hilari Sacalm que
persegueix el foment d'agrupar persones interessades en tecnologia de la zona de les Guilleries.

Ostres, la tecnologia està gairebé present a tot arreu avui en dia! Cert, però malgrat això, estem
en una àrea, que fins ara, no hi ha cap comunitat tècnica activa, i les que existeixen, estan
principalment en la província (Girona). Per tant, el que volem es tenir una comunitat i centrar-nos
en un camp específic (p. ex. desenvolupament web), llenguatge de programació (p. ex. Python), o
"framework" (p. ex. Ruby on Rails), ens dirigiria a fragmentar el grup de gent que està interessada
creant una comunitat molt poc activa, o inclús pitjor, no crear-ne cap.

Per tant, volem animar a tothom interessat en algun camp de la tecnologia, per exemple l'enginyeria
de "software", un llenguage de programació, un "framework", DevOps, IoT, SCADA, etc., que s'uneixi.
'''

[params.three]
enable = true
title = "El nostre objectiu"
body = '''
Volem unir la gent d'aquesta àrea geogràfica amb un interès general o específic de la tecnologia per
organitzar xerrades, trobades i esdeveniments (p. ex. hackathons).

Per aconseguir-ho, necessitem que la gent:
'''
[[params.three.feature]]
icon = 'fa-user'
body ='''
Es registri a la nostra comunitat amb la finalitat d'atendre a les activitats proposades quan siguin
del seu interès
'''
[[params.three.feature]]
icon = 'fa-lightbulb'
body ='''
Faci propostes, com xerrades sobre algun tema que sigui del seu interès, idees d'esdeveniments que
poden interessar a una part de la comunitat i els agradaria organitzar amb nosaltres
'''

[params.cta]
enable = true
title = "A què esperes?"
body = ""
[[params.cta.link]]
href = "sign-up-member"
text = "Registrat"
special = true
