[[main]]
name = 'Home'
pageRef = '/'
weight = 1
[[main]]
Name = 'Events'
pageRef = ''
weight = 10
[[main]]
Name = 'Upcoming'
pageRef = '/events-next'
weight = 1
parent = 'Events'
[[main]]
Name = 'Organization'
pageRef = '/organization-events'
weight = 5
parent = 'Events'
[[main]]
Name = 'Talk Proposal'
pageRef = '/talk-proposal'
weight = 15
[[main]]
Name = 'Sign up'
pageRef = '/sign-up-member'
weight = 100
[[main]]
Name = 'Code of conduct'
pageRef = '/code-conduct'
weight = 110
