[[main]]
name = 'Inici'
pageRef = '/'
weight = 1
[[main]]
Name = 'Codi de conducta'
pageRef = '/code-conduct'
weight = 5
[[main]]
Name = "Organització d'events"
pageRef = '/organization-events'
weight = 10
[[main]]
Name = 'Proposar'
pageRef = ''
weight = 15
[[main]]
Name = 'Xerrada'
pageRef = '/talk-proposal'
weight = 1
parent = 'Proposar'
[[main]]
Name = 'Registrat'
pageRef = '/sign-up-member'
weight = 100
